---
pretix_version: 2023.10.0

pretix_user: pretix
pretix_home_folder: /var/pretix
pretix_venv: "{{ pretix_home_folder }}/venv"
pretix_root_dir: /etc/pretix
pretix_data_dir: /var/pretix/data
pretix_media_dir: "{{ pretix_data_dir }}/media/"

pretix_pip_pkgs:
  # General
  - pretix=={{ pretix_version }}
  - gunicorn
  # Plugins
  - pretix-passbook

pretix_prerequisites:
  - git
  - build-essential
  - python3-dev
  - python3-venv
  - python3
  - python3-pip
  - python3-dev
  - libxml2-dev
  - libxslt1-dev
  - libffi-dev
  - zlib1g-dev
  - libssl-dev
  - gettext
  - libpq-dev
  - libjpeg-dev
  - libopenjp2-7-dev
