---
- name: Setup Pretix User
  ansible.builtin.user:
    name: "{{ pretix_user }}"
    state: present
    system: true
    home: "{{ pretix_home_folder }}"

- name: Setup Prerequisites
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ pretix_prerequisites }}"

- name: Setup Directories
  ansible.builtin.file:
    path: "{{ pretix_root_dir }}"
    state: directory
    owner: "{{ pretix_user }}"
    group: "{{ pretix_user }}"
    mode: "0755"

- name: Setup Pretix Configuration
  ansible.builtin.template:
    src: pretix.cfg.j2
    dest: "{{ pretix_root_dir }}/pretix.cfg"
    owner: "{{ pretix_user }}"
    group: "{{ pretix_user }}"
    mode: "0755"
  notify:
    - migrations

- name: Setup Environment
  become_user: "{{ pretix_user }}"
  ansible.builtin.pip:
    name:
      - pip
      - setuptools
      - wheel
    state: latest
    virtualenv: "{{ pretix_venv }}"
  notify:
    - migrations

- name: Setup Pretix Installation
  become_user: "{{ pretix_user }}"
  ansible.builtin.pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ pretix_venv }}"
  loop: "{{ pretix_pip_pkgs }}"
  notify:
    - migrations
    - restart_services

- name: Create data directory
  ansible.builtin.file:
    path: "{{ pretix_media_dir }}"
    state: directory
    owner: "{{ pretix_user }}"
    group: "{{ pretix_user }}"
    mode: "0755"

- name: Allow webserver access to the root directory
  ansible.builtin.file:
    path: "{{ pretix_home_folder }}"
    owner: "{{ pretix_user }}"
    group: "{{ pretix_user }}"
    mode: "0755"

- name: Setup Pretix Web Service
  ansible.builtin.template:
    src: pretix-web.service.j2
    dest: /etc/systemd/system/pretix-web.service
  notify:
    - Reload systemd
    - restart_services

- name: Setup Pretix Worker Service
  ansible.builtin.template:
    src: pretix-worker.service.j2
    dest: /etc/systemd/system/pretix-worker.service
  notify:
    - Reload systemd
    - restart_services

- name: Setup Pretix Services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    daemon_reload: true
    enabled: true
  loop:
    - pretix-web
    - pretix-worker

- name: Setup Cron Job
  ansible.builtin.cron:
    name: "pretix_runperiodic"
    minute: "15,45"
    job: "export PATH='{{ pretix_venv }}'/bin:$PATH && cd '{{ pretix_home_folder }}' && python -m pretix runperiodic"
    user: "{{ pretix_user }}"

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: Setup Cloudflared
  ansible.builtin.include_tasks: cloudflared_tunnel.yml
