---
- name: Deploy GCP Ops Agents
  hosts: pretix-prod-1
  become: true
  roles:
    - role: googlecloudplatform.google_cloud_ops_agents
      vars:
        agent_type: ops-agent

- name: Deploy Datadog Agent
  hosts: pretix-prod-1
  become: true
  tasks:
    - name: Import the Datadog Agent role from the Datadog collection
      ansible.builtin.import_role:
        name: datadog.dd.agent
  vars:
    datadog_api_key: "{{ lookup('ansible.builtin.env', 'DD_API_KEY') }}"
    datadog_site: "us5.datadoghq.com"
    datadog_config:
      tags:
        - "app:pretix"
      process_config:
        enabled: "true"
      apm_config:
        enabled: true
    system_probe_config:
      sysprobe_socket: /opt/datadog-agent/run/sysprobe.sock
    network_config:
      enabled: true
    service_monitoring_config:
      enabled: true
    runtime_security_config:
      enabled: true
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ["ssh", "sshd"]
      service_monitoring_config:
        enabled: true
      runtime_security_config:
        enabled: true
      redisdb:
        init_config:
        instances:
          - host: localhost
            port: 6379
      http_check:
        init_config:
        instances:
          - name: Pretix Service
            url: https://pretix.etcollective.org/healthcheck
            http_response_status_code: "200"
      openmetrics:
        init_config:
        instances:
          - openmetrics_endpoint: https://pretix.etcollective.org/metrics
            namespace: pretix
            auth_type: basic
            username: datadog-integration
            password: "{{ lookup('ansible.builtin.env', 'DD_API_KEY') }}"
            metrics:
              - pretix_*
            prometheus_metrics_prefix: pretix
            health_service_check: true

- name: Deploy Pretix
  hosts: pretix-prod-1
  become: true
  roles:
    - pretix
