---
# - name: Deploy GCP Ops Agents
#   hosts: pretix-prod-1
#   become: true
#   roles:
#     - role: googlecloudplatform.google_cloud_ops_agents
#       vars:
#         agent_type: ops-agent

# - name: Deploy Datadog Agent
#   hosts: pretix-prod-1
#   become: true
#   tasks:
#     - name: Import the Datadog Agent role from the Datadog collection
#       ansible.builtin.import_role:
#         name: datadog.dd.agent
#   vars:
#     datadog_api_key: "{{ lookup('ansible.builtin.env', 'DD_API_KEY') }}"
#     datadog_site: "us5.datadoghq.com"
#     service_monitoring_config:
#       enabled: true
#     datadog_config:
#       process_config:
#         enabled: "true"
#     datadog_checks:
#       process:
#         init_config:
#         instances:
#           - name: ssh
#             search_string: ["ssh", "sshd"]
#       service_monitoring_config:
#         enabled: true
#       runtime_security_config:
#         enabled: true
#       redisdb:
#         init_config:
#         instances:
#           - host: localhost
#             port: 6379
#       nginx:
#         init_config:
#         instances:

- name: Deploy Pretix
  hosts: pretix-prod-1
  become: true
  roles:
    - pretix
